title:       "Operating Systems 2021-1 (OS211)"
version:     "0027---27-Feb-2021"
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
author:           "Theophilus Lukas"
address:          "1906398332"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://theophilus-lukas.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/Theophilus-Lukas/os211"
urlghpage:        "https://theophilus-lukas.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]

